apiVersion: shipwright.io/v1alpha1
kind: Build
metadata:
  name: devops-toolkit
  annotations:
    build.build.dev/build-run-deletion: "true"
spec:
  source:
    url: https://github.com/vfarcic/shipwright-demo
  strategy:
    name: kaniko
    kind: ClusterBuildStrategy
  output:
    image: docker.io/vfarcic/devops-toolkit:latest
    credentials:
      name: regcred
